### ISSUE TITLE
Supporting multiple open files

### ISSUE THREAD

**Issue by Gladdy** [bbenoist/vscode-togglehs#2]
Hi, I was trying out your plugin for VSCode, but when I attempt to use it with multiple files open (active and cursor in the rightmost file), on pressing F4, it replaces my the file I have open on the left with the header of the source file on the right. When pressing F4 again, it switches the leftmost file to the source file, leaving me with the same file opened twice.

I really like this plugin but the fact that it only works properly on the leftmost opened file doesn't add to its usefulness.

**Comment by bbenoist** [comment]
Hi,

Thanks for the legitimate feedback!

I too am very sad I couldn't find a way to tell VSCode to load new file in current panel. Last time I tried, I saw no option for this 😢 

As this issue is very problematic, I will check again what can I do and update the issue accordingly.

**Comment by bbenoist** [comment]
@Gladdy I've released version 0.1.1 with the fix for this issue 🎉 

As the needed information doesn't seem to be officially accessible for now, I had to access a private property of the `TextEditor` object from the API.

**Comment by bbenoist** [comment]
@Gladdy New version 0.1.2 should be more reliable than 0.1.1. I've updated the dependencies to use vscode engine 1.0.0 which has the information I was looking for...

**Comment by Gladdy** [comment]
Thank you! it works great. I wasn't sure how to update the plugin, but completely reinstalling it got me the new version.
